#!/bin/bash

KAFKA1_IP=172.28.11.1 # port 9092
KAFKA2_IP=172.28.11.2 # port 9092
KAFKA3_IP=172.28.11.3 # port 9092

docker run -d \
  --name kafka-1 -h kafka-1 \
  --network arangodb --ip "$KAFKA1_IP" \
  -e BITNAMI_DEBUG=true \
  -e ALLOW_PLAINTEXT_LISTENER="yes" \
  -e KAFKA_CFG_NODE_ID=0 \
  -e KAFKA_CFG_CONTROLLER_QUORUM_VOTERS="0@$KAFKA1_IP:9093,1@$KAFKA2_IP:9093,2@$KAFKA3_IP:9093" \
  -e KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv \
  -e KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER \
  -e KAFKA_CFG_ADVERTISED_LISTENERS="PLAINTEXT://$KAFKA1_IP:9092" \
  -e KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT \
  -e KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT \
  docker.io/bitnami/kafka:3.4

docker run -d \
  --name kafka-2 -h kafka-2 \
  --network arangodb --ip "$KAFKA2_IP" \
  -e BITNAMI_DEBUG=true \
  -e ALLOW_PLAINTEXT_LISTENER="yes" \
  -e KAFKA_CFG_NODE_ID=1 \
  -e KAFKA_CFG_CONTROLLER_QUORUM_VOTERS="0@$KAFKA1_IP:9093,1@$KAFKA2_IP:9093,2@$KAFKA3_IP:9093" \
  -e KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv \
  -e KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER \
  -e KAFKA_CFG_ADVERTISED_LISTENERS="PLAINTEXT://$KAFKA2_IP:9092" \
  -e KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT \
  -e KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT \
  docker.io/bitnami/kafka:3.4

docker run -d \
  --name kafka-3 -h kafka-3 \
  --network arangodb --ip "$KAFKA3_IP" \
  -e BITNAMI_DEBUG=true \
  -e ALLOW_PLAINTEXT_LISTENER="yes" \
  -e KAFKA_CFG_NODE_ID=2 \
  -e KAFKA_CFG_CONTROLLER_QUORUM_VOTERS="0@$KAFKA1_IP:9093,1@$KAFKA2_IP:9093,2@$KAFKA3_IP:9093" \
  -e KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv \
  -e KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER \
  -e KAFKA_CFG_ADVERTISED_LISTENERS="PLAINTEXT://$KAFKA3_IP:9092" \
  -e KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT \
  -e KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT \
  docker.io/bitnami/kafka:3.4

echo ""
echo ""
echo "Done, your deployment is reachable at: "
echo "Kafka:          $KAFKA1_IP:9092,$KAFKA2_IP:9092,$KAFKA3_IP:9092"
