name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docker/**'
      - 'ChangeLog.md'
      - 'README.md'
  pull_request:
    branches:
      - main

jobs:
  standalone:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: ${{matrix.topology}}, ${{matrix.java-version}}

    strategy:
      fail-fast: false
      matrix:
        arango-version:
          - 3.11.1
        topology:
          - cluster
        java-version:
          - 20

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{matrix.java-version}}
          distribution: 'temurin'
          cache: maven
      - name: Create Network
        run: ./docker/create_network.sh
      - name: Start Kafka
        run: ./docker/start_kafka.sh
      - name: Start Schema Registry
        run: ./docker/start_schema_registry.sh
      - name: Start Database
        run: ./docker/start_db.sh
        env:
          STARTER_MODE: ${{matrix.topology}}
          DOCKER_IMAGE: docker.io/arangodb/arangodb:${{matrix.arango-version}}
      - name: Integration Tests
        run: mvn integration-test

  cluster:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: ${{matrix.topology}}, ${{matrix.java-version}}
    env:
      KAFKA_CONNECT_HOST: "http://172.28.11.11:8083"

    strategy:
      fail-fast: false
      matrix:
        arango-version:
          - 3.11.1
        topology:
          - single
        java-version:
          - 8
          - 11
          - 17

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{matrix.java-version}}
          distribution: 'temurin'
          cache: maven
      - name: Package
        run: mvn package
      - name: Create Network
        run: ./docker/create_network.sh
      - name: Start Kafka
        run: ./docker/start_kafka.sh
      - name: Start Schema Registry
        run: ./docker/start_schema_registry.sh
      - name: Start Database
        run: ./docker/start_db.sh
        env:
          STARTER_MODE: ${{matrix.topology}}
          DOCKER_IMAGE: docker.io/arangodb/arangodb:${{matrix.arango-version}}
      - name: Start Kafka Connect
        run: ./docker/start_kafka_connect.sh
      - name: Integration Tests
        run: mvn integration-test -Dkafka.connect.host=${{env.KAFKA_CONNECT_HOST}}
